name: Docker Image CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        ghc: ["8.6.5", "8.8.3"]
        lsp: ["hie", "hls", "ghcide", "all"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./.devcontainer/ --file ./.devcontainer/Dockerfile --tag vlza/haskelldevenv:${{ matrix.ghc }}-${{ matrix.lsp }}-$(date +%s)

# TODO: Trigger release on tag, publish containers.
